# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f82aeb08bb7e584b3381636ac8c19622f8c036120c8f26eb85216fde542ed174c384e30507be845c03b6d09ac1da5a9eb6490a23747496429c1736679d87e17

test:
  secret_key_base: 182ac605c63d3bc6ccf1ad75acd4584ca462c479a78217a6675bbc072da42282d66595ce90b31d2b86ee722bec233e958db706fe081b5c2558e52647dadeff58

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
